### ISSUE TITLE
nice tool !

### ISSUE THREAD

**Issue by Pop-Apple** [Korozin/Minecraft-Wii-U-Pixel-Art-Tool#1]
I'm Japanese but  
I hate paying for Wii U cheats 😉

**Comment by Korozin** [comment]
Agreed. Paying for cheats is kind of ridiculous as most of the things being sold were just stolen anyways.

Also I saw your branch of this. Good work on it! I just wanna say though, the original creator was actually MinecraftWiiUCodes, I just edited it slightly and then compiled it for other people.

**Comment by Pop-Apple** [comment]
I see  
Thank You Korozin 😘
